CREATE TABLE "GCG_5755_SHIPINFO" (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "ORDER_NUM" CHAR(50),
 "BIN" CHAR(6),
 "QTY" DOUBLE,
 "GROSS_WT" DOUBLE,
 "TARE_WT" DOUBLE,
 "NET_WT" DOUBLE,
 "APW" DOUBLE,
 "ORDER_LINE" CHAR(50),
 "PACKLIST" CHAR(50) );